version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./:/var/www/html
      - ./docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_INTERNAL_URL: http://app:8000
      LOGIN_2FA_ENABLED: 'false'
      DB_CONNECTION: sqlsrv
      DB_HOST: SQL9001.site4now.net
      DB_PORT: 1433
      DB_DATABASE: db_ac9b40_aigobernance
      DB_USERNAME: db_ac9b40_aigobernance_admin
      DB_PASSWORD: "GestionTI24!"
      MAIL_MAILER: smtp
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_USERNAME: juanesteban24082005@gmail.com
      MAIL_PASSWORD: kvcpuryjyhczqlhl
      MAIL_ENCRYPTION: tls
      MAIL_FROM_ADDRESS: juanesteban24082005@gmail.com
      MAIL_FROM_NAME: "ProyectoGestion"
      JWT_SECRET: base64:g0kCkG4WuH9o3WZPwzE1yqG7lcHOIdyZFh0bKd9Pp2E=
      JWT_ALGORITHM: HS256
      JWT_EXPIRATION_HOURS: 24
      JWT_ACTIVATION_URL: http://localhost:8000/verify-email
      TWILIO_ACCOUNT_SID: AC0c16a8323259c0863503e01f6ac97c31
      TWILIO_AUTH_TOKEN: b6668110c068f89abf8d2d63936d6f6b
      TWILIO_PHONE_NUMBER: "+16788248182"
      N8N_WEBHOOK_URL: http://n8n:5678/webhook/Evaluacion
    depends_on:
      - node
      - n8n

  node:
    image: node:18
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: sh -c "npm ci --silent && npm run build --silent"

  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      N8N_HOST: 0.0.0.0
      N8N_PORT: 5678
      N8N_PROTOCOL: http
      WEBHOOK_URL: http://localhost:5678/
      N8N_EDITOR_BASE_URL: http://localhost:5678/
      GENERIC_TIMEZONE: America/Bogota
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
