version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      DB_CONNECTION: sqlsrv
      DB_HOST: SQL9001.site4now.net
      DB_PORT: 1433
      DB_DATABASE: db_ac9b40_aigobernance
      DB_USERNAME: db_ac9b40_aigobernance_admin
      DB_PASSWORD: "GestionTI24!"
    depends_on:
      - node

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: proyecto_gestion
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  node:
    image: node:18
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: sh -c "npm ci --silent && npm run build --silent"
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - "8080:80"

volumes:
  db_data:
